In [1]:
from sklearn.datasets import load_iris
iris_data=load_iris()


In [2]:
dir(iris_data)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
X=iris_data.data
X.shape


(150, 4)

In [4]:
y=iris_data.target
y.shape

(150,)

In [5]:
type(X)

numpy.ndarray

In [6]:
print(iris_data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

In [8]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression
#
logModel=LogisticRegression()
logModel.fit(X_train,y_train)


LogisticRegression()

In [10]:
logModel.score(X_train,y_train)

0.9732142857142857

In [11]:
logModel.score(X_test,y_test)

0.9736842105263158

In [12]:
y_predict=logModel.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test,y_predict))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [14]:
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import KFold
# import numpy as np
# logModel2=LogisticRegression()
# cross_val_scores=cross_val_score(estimator=logModel2,X=X_train,y=y_train,scoring="f1_weighted")
# np.mean(cross_val_scores)

In [15]:
# from sklearn import metrics
# sorted(metrics.SCORERS.keys())